# Generated by Django 5.2.11 on 2026-03-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='achieved',
            field=models.BooleanField(default=False),
        ),
    ]
