# Generated by Django 5.2.11 on 2026-03-01 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_goal_achieved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='achieved',
        ),
    ]
